-- Replica Bone — light
-- Reproduction of paper at noon.
-- Generated from replica.json v0.6.0. Do not edit by hand.

vim.cmd("highlight clear")
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end
vim.o.background = "light"
vim.g.colors_name = "replica-bone"

local p = {
  base = "#e6e0d5",
  surface = "#eee9e0",
  overlay = "#f4f0e9",
  muted = "#857c70",
  subtle = "#6e665b",
  text = "#3d3833",
  clay = "#a2431d",
  flax = "#715840",
  sulfur = "#715d06",
  resin = "#49601c",
  slate = "#3d6070",
  ash = "#755c6b",
  oxide = "#7c1f1f",
  highlightLow = "#ded8cc",
  highlightMed = "#d8d1c5",
  highlightHigh = "#c8c0b1",
}

local groups = {
  ["Normal"] = { fg = p.text, bg = p.base },
  ["NormalNC"] = { fg = p.text, bg = p.base },
  ["NormalFloat"] = { fg = p.text, bg = p.overlay },
  ["FloatBorder"] = { fg = p.highlightHigh, bg = p.overlay },
  ["FloatTitle"] = { fg = p.slate, bg = p.overlay, bold = true },
  ["Cursor"] = { fg = p.base, bg = p.slate },
  ["lCursor"] = { fg = p.base, bg = p.slate },
  ["TermCursor"] = { fg = p.base, bg = p.slate },
  ["CursorLine"] = { bg = p.highlightLow },
  ["CursorColumn"] = { bg = p.highlightLow },
  ["ColorColumn"] = { bg = p.surface },
  ["CursorLineNr"] = { fg = p.text, bold = true },
  ["LineNr"] = { fg = p.muted },
  ["SignColumn"] = { fg = p.muted },
  ["FoldColumn"] = { fg = p.muted },
  ["Folded"] = { fg = p.subtle, bg = p.surface },
  ["Visual"] = { bg = p.highlightMed },
  ["VisualNOS"] = { bg = p.highlightMed },
  ["Search"] = { fg = p.base, bg = p.sulfur },
  ["IncSearch"] = { fg = p.base, bg = p.clay },
  ["CurSearch"] = { fg = p.base, bg = p.clay },
  ["MatchParen"] = { fg = p.clay, bg = p.highlightHigh, bold = true },
  ["StatusLine"] = { fg = p.subtle, bg = p.surface },
  ["StatusLineNC"] = { fg = p.muted, bg = p.surface },
  ["WinBar"] = { fg = p.subtle },
  ["WinBarNC"] = { fg = p.muted },
  ["WinSeparator"] = { fg = p.highlightHigh },
  ["VertSplit"] = { fg = p.highlightHigh },
  ["TabLine"] = { fg = p.muted, bg = p.surface },
  ["TabLineSel"] = { fg = p.text, bg = p.overlay },
  ["TabLineFill"] = { bg = p.base },
  ["Pmenu"] = { fg = p.subtle, bg = p.overlay },
  ["PmenuSel"] = { fg = p.text, bg = p.highlightMed },
  ["PmenuSbar"] = { bg = p.overlay },
  ["PmenuThumb"] = { bg = p.highlightHigh },
  ["Directory"] = { fg = p.slate },
  ["Title"] = { fg = p.clay, bold = true },
  ["Question"] = { fg = p.resin },
  ["ModeMsg"] = { fg = p.subtle },
  ["MoreMsg"] = { fg = p.resin },
  ["ErrorMsg"] = { fg = p.oxide },
  ["WarningMsg"] = { fg = p.sulfur },
  ["NonText"] = { fg = p.muted },
  ["Whitespace"] = { fg = p.muted },
  ["SpecialKey"] = { fg = p.muted },
  ["EndOfBuffer"] = { fg = p.base },
  ["Conceal"] = { fg = p.subtle },
  ["QuickFixLine"] = { bg = p.highlightMed },
  ["Substitute"] = { fg = p.base, bg = p.clay },
  ["WildMenu"] = { fg = p.base, bg = p.clay },
  ["Comment"] = { fg = p.ash, italic = true },
  ["Constant"] = { fg = p.sulfur },
  ["String"] = { fg = p.flax },
  ["Character"] = { fg = p.flax },
  ["Number"] = { fg = p.sulfur },
  ["Boolean"] = { fg = p.sulfur },
  ["Float"] = { fg = p.sulfur },
  ["Identifier"] = { fg = p.text },
  ["Function"] = { fg = p.slate },
  ["Statement"] = { fg = p.clay },
  ["Conditional"] = { fg = p.clay },
  ["Repeat"] = { fg = p.clay },
  ["Label"] = { fg = p.clay },
  ["Operator"] = { fg = p.subtle },
  ["Keyword"] = { fg = p.clay },
  ["Exception"] = { fg = p.clay },
  ["PreProc"] = { fg = p.clay },
  ["Include"] = { fg = p.clay },
  ["Define"] = { fg = p.clay },
  ["Macro"] = { fg = p.clay },
  ["PreCondit"] = { fg = p.clay },
  ["Type"] = { fg = p.resin },
  ["StorageClass"] = { fg = p.clay },
  ["Structure"] = { fg = p.resin },
  ["Typedef"] = { fg = p.resin },
  ["Special"] = { fg = p.sulfur },
  ["SpecialChar"] = { fg = p.sulfur },
  ["Tag"] = { fg = p.resin },
  ["Delimiter"] = { fg = p.subtle },
  ["SpecialComment"] = { fg = p.ash, italic = true },
  ["Debug"] = { fg = p.oxide },
  ["Underlined"] = { fg = p.slate, underline = true },
  ["Ignore"] = { fg = p.muted },
  ["Error"] = { fg = p.oxide },
  ["Todo"] = { fg = p.base, bg = p.sulfur, bold = true },
  ["@comment"] = { fg = p.ash, italic = true },
  ["@keyword"] = { fg = p.clay },
  ["@keyword.function"] = { fg = p.clay },
  ["@keyword.operator"] = { fg = p.clay },
  ["@keyword.return"] = { fg = p.clay },
  ["@keyword.import"] = { fg = p.clay },
  ["@keyword.conditional"] = { fg = p.clay },
  ["@keyword.repeat"] = { fg = p.clay },
  ["@keyword.exception"] = { fg = p.clay },
  ["@string"] = { fg = p.flax },
  ["@string.escape"] = { fg = p.sulfur },
  ["@string.regexp"] = { fg = p.flax },
  ["@string.special"] = { fg = p.sulfur },
  ["@character"] = { fg = p.flax },
  ["@number"] = { fg = p.sulfur },
  ["@boolean"] = { fg = p.sulfur },
  ["@float"] = { fg = p.sulfur },
  ["@constant"] = { fg = p.sulfur },
  ["@constant.builtin"] = { fg = p.sulfur },
  ["@constant.macro"] = { fg = p.sulfur },
  ["@type"] = { fg = p.resin },
  ["@type.builtin"] = { fg = p.resin },
  ["@type.definition"] = { fg = p.resin },
  ["@attribute"] = { fg = p.flax },
  ["@property"] = { fg = p.text },
  ["@field"] = { fg = p.text },
  ["@variable"] = { fg = p.text },
  ["@variable.builtin"] = { fg = p.clay },
  ["@variable.parameter"] = { fg = p.text },
  ["@variable.member"] = { fg = p.text },
  ["@function"] = { fg = p.slate },
  ["@function.call"] = { fg = p.slate },
  ["@function.builtin"] = { fg = p.slate },
  ["@function.macro"] = { fg = p.slate },
  ["@method"] = { fg = p.slate },
  ["@method.call"] = { fg = p.slate },
  ["@constructor"] = { fg = p.resin },
  ["@module"] = { fg = p.resin },
  ["@namespace"] = { fg = p.resin },
  ["@label"] = { fg = p.clay },
  ["@operator"] = { fg = p.subtle },
  ["@punctuation.delimiter"] = { fg = p.subtle },
  ["@punctuation.bracket"] = { fg = p.subtle },
  ["@punctuation.special"] = { fg = p.clay },
  ["@tag"] = { fg = p.resin },
  ["@tag.builtin"] = { fg = p.resin },
  ["@tag.attribute"] = { fg = p.flax },
  ["@tag.delimiter"] = { fg = p.subtle },
  ["@markup.heading"] = { fg = p.clay, bold = true },
  ["@markup.strong"] = { fg = p.clay, bold = true },
  ["@markup.italic"] = { fg = p.flax, italic = true },
  ["@markup.link"] = { fg = p.slate, underline = true },
  ["@markup.link.url"] = { fg = p.slate, underline = true },
  ["@markup.raw"] = { fg = p.flax },
  ["@markup.list"] = { fg = p.subtle },
  ["@markup.quote"] = { fg = p.flax, italic = true },
  ["@diff.plus"] = { fg = p.resin },
  ["@diff.minus"] = { fg = p.oxide },
  ["@lsp.type.class"] = { fg = p.resin },
  ["@lsp.type.interface"] = { fg = p.resin },
  ["@lsp.type.enum"] = { fg = p.resin },
  ["@lsp.type.function"] = { fg = p.slate },
  ["@lsp.type.method"] = { fg = p.slate },
  ["@lsp.type.namespace"] = { fg = p.resin },
  ["@lsp.type.parameter"] = { fg = p.text },
  ["@lsp.type.property"] = { fg = p.text },
  ["@lsp.type.variable"] = { fg = p.text },
  ["@lsp.type.keyword"] = { fg = p.clay },
  ["@lsp.type.comment"] = { fg = p.ash, italic = true },
  ["DiagnosticError"] = { fg = "#7c1f1f" },
  ["DiagnosticVirtualTextError"] = { fg = "#7c1f1f", bg = p.surface },
  ["DiagnosticUnderlineError"] = { sp = "#7c1f1f", undercurl = true },
  ["DiagnosticWarn"] = { fg = "#715d06" },
  ["DiagnosticVirtualTextWarn"] = { fg = "#715d06", bg = p.surface },
  ["DiagnosticUnderlineWarn"] = { sp = "#715d06", undercurl = true },
  ["DiagnosticInfo"] = { fg = "#3d6070" },
  ["DiagnosticVirtualTextInfo"] = { fg = "#3d6070", bg = p.surface },
  ["DiagnosticUnderlineInfo"] = { sp = "#3d6070", undercurl = true },
  ["DiagnosticHint"] = { fg = "#755c6b" },
  ["DiagnosticVirtualTextHint"] = { fg = "#755c6b", bg = p.surface },
  ["DiagnosticUnderlineHint"] = { sp = "#755c6b", undercurl = true },
  ["DiffAdd"] = { bg = "#cac9b4" },
  ["DiffDelete"] = { bg = "#d3bdb4" },
  ["DiffChange"] = { bg = "#cecec7" },
  ["DiffText"] = { bg = "#babfbb" },
  ["GitSignsAdd"] = { fg = p.resin },
  ["GitSignsChange"] = { fg = p.sulfur },
  ["GitSignsDelete"] = { fg = p.oxide },
}

for group, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, group, spec)
end

-- Opt-in transparency: let the terminal background through, so a
-- translucent/blurred terminal keeps working. Set before loading.
if vim.g.replica_transparent then
  local seethrough = {
    Normal = p.text,
    NormalNC = p.text,
    NormalFloat = p.text,
    SignColumn = p.muted,
    FoldColumn = p.muted,
    EndOfBuffer = p.base,
    TabLineFill = p.muted,
  }
  for group, fg in pairs(seethrough) do
    vim.api.nvim_set_hl(0, group, { fg = fg, bg = "NONE" })
  end
end

-- Terminal colors, from the palette's own ansi16 port values.
vim.g.terminal_color_0 = "#3d3833"
vim.g.terminal_color_1 = "#7c1f1f"
vim.g.terminal_color_2 = "#49601c"
vim.g.terminal_color_3 = "#715d06"
vim.g.terminal_color_4 = "#3d6070"
vim.g.terminal_color_5 = "#755c6b"
vim.g.terminal_color_6 = "#436046"
vim.g.terminal_color_7 = "#eee9e0"
vim.g.terminal_color_8 = "#6e665b"
vim.g.terminal_color_9 = "#6d1b1b"
vim.g.terminal_color_10 = "#405419"
vim.g.terminal_color_11 = "#635205"
vim.g.terminal_color_12 = "#365463"
vim.g.terminal_color_13 = "#67515e"
vim.g.terminal_color_14 = "#3b543e"
vim.g.terminal_color_15 = "#e6e0d5"
